### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by jamesadevine** [iot-chalmers/BlueFlood#1]
Hi BlueFlood team!

Independently over the past 2 years I've been applying Glossy principles ("constructive interference") the nrf51 series of nordic chips. After implementing the wireless protocol in a number of different ways I do not believe the effect is constructive interference, but rather more like the transceiver locking onto a specific device. 

Theoretically if the physics is correct and timing is precise enough, concurrent transmissions should result in the concurrent signal being as good as a transmitter _without_ any concurrent transmissions. From my investigations however, this is simply not true. Within 2 metres devices have variable reception rates seemingly depending on which way the wind is blowing... :smile: I assume this is down to multipath and reflections, although this seems unlikely considering I'm not communicating with devices 100s of metres away.

I note in your paper only the concurrent transmission effect using coax cables is reported and your evaluation of BlueFlood mentions only _packets_ received and not _frames_ received (an important metric nevertheless). So i'm left wondering if your team saw a similar effect and came to similar conclusions. 

If we could compare notes, that would be great :smile:

**Comment by romain-jacob** [comment]
Hi James,

(I am not from the BluEFlood team, but...)

It is indeed the understanding of most concurrent/synchronous transmissions (ST) specialists that there is more than just CI happening. To be more precise: CI only does not explain why packets are successfully received. 

The issue is that, as far as I know, the theoretical understanding of what is going on is... sparse. Yes, we know about the different effects that come into play (capture effect, frequency locking, coding, etc.), but it is difficult to experimentally validate what is going on precisely, mainly due the inherent variability of the experimental conditions. 

We recently tried to [thoroughly investigate the conditions for successful ST using nRF52 dongles](https://www.research-collection.ethz.ch/handle/20.500.11850/375332). This provides some more evidence of what we already knew, but we are not quite yet at the point where we can clearly connect theory and practice. If you are some thoughts/time to share to progress on this, we should talk :-)

Cheers,
-- 
Romain

**Comment by olafland** [comment]
Hi James, Romain, 

@James: very nice to hear from you and thanks for your interest. We are very happy to compare notes. Moreover, we tried to add some theory, so maybe there are some insights to share. 

@Romain: thanks for the master thesis, we are looking at it right now. On a first glance It is very much inline with our results from EWSN (and newer ones we are preparing now), but we need to look deeper to double check. 

@both: shall we have a joint Skype call to discuss. James, we know Romain his group at ETH very well and share our results openly with them. Thus, I hope that a joint call is fine for you. 

Best,
Olaf

**Comment by beshrns** [comment]
Hi James, Romain, Olaf,

Thanks for the nice discussion. 
I agree with Olaf that it makes sense to have a call.

Regarding the CT discussion: based on the results I have, it is more likely that what is happening is actually distructive interference that depends on the carrier frequency difference between the boards and the power difference. If the power difference is low, the deciding factor is the frequency difference. The higher it is, the worse the signal quality. 
In testbed experiments, due to multipath fading, it is very unlikely for the signals to have the same power at the receiver, as pointed out by James. Thus, it becomes a power capture.
Let's discuss more on Skype.

@jamesadevine You can reach me at beshr-at-chalmers-dot-se or my GitHub email.
